/**
 * DataForSEO SERP provider (v7.397)
 * ───────────────────────────────────────────────────────────────────────────
 * A second SERP source behind the SAME contract SerpAPI already satisfies, so
 * `lib/apis/serp.ts` can dispatch to either provider without one downstream
 * caller changing. Every function here returns the EXACT types serp.ts returns
 * (imported as types below — `import type` is erased at compile time, so there
 * is no runtime cycle even though serp.ts imports this module).
 *
 * WHY (Wayne, 2026-08-03): SerpAPI is 76% of OrbitIQ's API bill ($219.27 of
 * $288.49) and carries a hard 30,000-searches/month ceiling that a single large
 * client can eat half of in one analysis (US Bank: 13,788 searches). DataForSEO
 * is pay-as-you-go with no ceiling at $0.002/SERP live vs SerpAPI's $0.0091667
 * effective — and it is the only provider in OrbitIQ that reports the REAL cost
 * of each request in its own response.
 *
 * ⭐ MEASURED COST (Const I.1). The response carries `cost` per task. That is a
 * real source row, not a rate × count estimate, so the usage ledger records the
 * ACTUAL dollars charged for every call. This is the first and only source in
 * OrbitIQ where spend is measured rather than derived; the published rate is
 * kept in the registry purely as a cross-check.
 *
 * Auth: HTTP Basic with the API login + API password from the DataForSEO
 * dashboard's API Access tab (the API password is generated by DataForSEO and
 * is NOT the account password). Docs: https://docs.dataforseo.com/v3/auth/
 *
 * Fault-tolerant by construction, exactly like serp.ts: every function catches
 * and returns an empty/false result so one bad call can never break a scan.
 */

import type {
  SerpResult, AIOSource, PAASource, VideoSource,
  KeywordSerpData, MapsPlace, LocalPackResult,
} from './serp';
import type { Market } from '@/lib/utils/markets';
import { getMarket } from '@/lib/utils/markets';
import { recordDataForSeo } from '@/lib/usage/record';

const DFS_BASE = 'https://api.dataforseo.com/v3';
const ORGANIC_ENDPOINT = '/serp/google/organic/live/advanced';
const MAPS_ENDPOINT    = '/serp/google/maps/live/advanced';

/** True only when both Basic-auth halves are configured. */
export function dataForSeoEnabled(): boolean {
  return !!process.env.DATAFORSEO_LOGIN && !!process.env.DATAFORSEO_PASSWORD;
}

function authHeader(): string | null {
  const login = process.env.DATAFORSEO_LOGIN;
  const pass  = process.env.DATAFORSEO_PASSWORD;
  if (!login || !pass) return null;
  // Node runtime — Buffer is available in the Vercel lambda.
  return 'Basic ' + Buffer.from(`${login}:${pass}`).toString('base64');
}

/**
 * SerpAPI's `ll` is "@lat,lng,<zoom>z"; DataForSEO's `location_coordinate` is
 * "lat,lng,<zoom>z" with no leading @ and at most 7 decimal places. Returns
 * null when the input isn't a coordinate string we can trust (never guesses).
 */
export function llToLocationCoordinate(ll?: string): string | null {
  if (!ll) return null;
  const cleaned = ll.trim().replace(/^@/, '');
  const parts = cleaned.split(',').map(s => s.trim()).filter(Boolean);
  if (parts.length < 2) return null;
  const lat = Number(parts[0]);
  const lng = Number(parts[1]);
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null;
  const round7 = (n: number) => String(Number(n.toFixed(7)));
  const zoomRaw = parts[2] ?? '';
  const zoom = /^\d+z?$/.test(zoomRaw) ? (zoomRaw.endsWith('z') ? zoomRaw : `${zoomRaw}z`) : '17z';
  return `${round7(lat)},${round7(lng)},${zoom}`;
}

interface DfsCall<T> { result: T | null; costUSD: number; }

/**
 * POST one live task. Returns the first result object plus the REAL cost the
 * API reported, and records that measured cost in the usage ledger.
 */
async function dfsPost<T = any>(endpoint: string, task: Record<string, unknown>, ledgerEndpoint: string, ledgerUnit: 'searches' | 'llm_mentions' = 'searches'): Promise<DfsCall<T>> {
  const auth = authHeader();
  if (!auth) return { result: null, costUSD: 0 };
  try {
    const res = await fetch(`${DFS_BASE}${endpoint}`, {
      method: 'POST',
      headers: { 'Authorization': auth, 'Content-Type': 'application/json' },
      body: JSON.stringify([task]),                 // DataForSEO takes an ARRAY of tasks
      signal: AbortSignal.timeout(20_000),
    });
    if (!res.ok) {
      console.error(`DataForSEO ${ledgerEndpoint} HTTP ${res.status}`);
      return { result: null, costUSD: 0 };
    }
    const body: any = await res.json();
    // status_code 20000 = OK. Anything else is a real failure, surfaced as empty.
    if (Number(body?.status_code) !== 20000) {
      console.error(`DataForSEO ${ledgerEndpoint} status ${body?.status_code}: ${body?.status_message}`);
      return { result: null, costUSD: 0 };
    }
    const t0 = Array.isArray(body?.tasks) ? body.tasks[0] : null;
    // Per-task cost when present, else the envelope total. Never invented.
    const costUSD = Number(t0?.cost ?? body?.cost ?? 0) || 0;
    // Record the MEASURED dollars (Const I.1) — 1 request = 1 search unit.
    await recordDataForSeo(ledgerEndpoint, costUSD, 1, process.env.DATAFORSEO_LOGIN, ledgerUnit);
    if (Number(t0?.status_code) !== 20000) {
      console.error(`DataForSEO ${ledgerEndpoint} task status ${t0?.status_code}: ${t0?.status_message}`);
      return { result: null, costUSD };
    }
    const result = Array.isArray(t0?.result) ? t0.result[0] : null;
    return { result: (result ?? null) as T | null, costUSD };
  } catch (err) {
    console.error(`DataForSEO ${ledgerEndpoint} fetch failed:`, err);
    return { result: null, costUSD: 0 };
  }
}

function extractDomain(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, '');
  } catch {
    return url;
  }
}

function isClient(domain: string, clientDomain: string): boolean {
  const c = (clientDomain ?? '').replace(/^www\./, '').toLowerCase();
  const d = (domain ?? '').replace(/^www\./, '').toLowerCase();
  return !!c && !!d && (d === c || d.endsWith(`.${c}`));
}

/** Flatten DataForSEO's ai_overview element tree into plain text. Verbatim only. */
function extractAioText(aio: any): string | undefined {
  const out: string[] = [];
  const walk = (nodes: any[]) => {
    for (const n of nodes ?? []) {
      if (!n || typeof n !== 'object') continue;
      if (typeof n.text === 'string' && n.text.trim()) out.push(n.text.trim());
      if (Array.isArray(n.items)) walk(n.items);
    }
  };
  walk(Array.isArray(aio?.items) ? aio.items : []);
  const joined = out.join('\n').trim();
  return joined ? joined.slice(0, 6000) : undefined;   // same 6000-char bound serp.ts uses
}

/** AI Overview citations. DataForSEO exposes them as `references` and/or per-element links. */
function extractAioSources(aio: any): AIOSource[] {
  const seen = new Set<string>();
  const out: AIOSource[] = [];
  const push = (title: any, url: any, domain: any) => {
    const u = typeof url === 'string' ? url : '';
    if (!u || seen.has(u)) return;
    seen.add(u);
    out.push({
      title:  typeof title === 'string' ? title : '',
      url:    u,
      domain: typeof domain === 'string' && domain ? domain.replace(/^www\./, '') : extractDomain(u),
    });
  };
  (Array.isArray(aio?.references) ? aio.references : []).forEach((r: any) => push(r?.title, r?.url, r?.domain));
  const walk = (nodes: any[]) => {
    for (const n of nodes ?? []) {
      if (!n || typeof n !== 'object') continue;
      (Array.isArray(n.links) ? n.links : []).forEach((l: any) => push(l?.title, l?.url, l?.domain));
      (Array.isArray(n.references) ? n.references : []).forEach((l: any) => push(l?.title, l?.url, l?.domain));
      if (Array.isArray(n.items)) walk(n.items);
    }
  };
  walk(Array.isArray(aio?.items) ? aio.items : []);
  return out;
}

/**
 * Scan a batch of keywords through DataForSEO and return the SAME
 * KeywordSerpData[] SerpAPI's batchKeywordScan returns.
 */
export async function dfsBatchKeywordScan(
  keywords: string[],
  clientDomain: string,
  limit = 5,
  market?: Market,
): Promise<KeywordSerpData[]> {
  if (!dataForSeoEnabled()) return [];
  const m = market ?? getMarket('us');
  const batch = keywords.slice(0, limit);
  const CONCURRENCY = 5;                 // mirrors serp.ts SCAN_CONCURRENCY
  const out: KeywordSerpData[] = [];

  async function scanOne(keyword: string): Promise<KeywordSerpData | null> {
    const { result } = await dfsPost<any>(ORGANIC_ENDPOINT, {
      keyword,
      location_name: m.dfsLocationName,
      language_code: m.dfsLanguageCode,
      device: 'desktop',
      depth: 10,
      load_async_ai_overview: true,      // AI Overview is a first-class OrbitIQ signal
    }, 'google_organic');
    if (!result) return null;

    const items: any[] = Array.isArray(result.items) ? result.items : [];
    const itemTypes: string[] = Array.isArray(result.item_types) ? result.item_types.slice() : [];

    const organicResults: SerpResult[] = [];
    let featuredSnippet: SerpResult | null = null;
    let hasAIO = false;
    let aioSources: AIOSource[] = [];
    let aioText: string | undefined;
    const paaQuestions: string[] = [];
    const paaSources: PAASource[] = [];
    const videoSources: VideoSource[] = [];

    for (const it of items) {
      const type = it?.type;
      if (type === 'organic') {
        const url = it?.url ?? '';
        organicResults.push({
          position: Number(it?.rank_group) || organicResults.length + 1,
          title:    it?.title ?? '',
          url,
          domain:   it?.domain ? String(it.domain).replace(/^www\./, '') : extractDomain(url),
          snippet:  it?.description ?? undefined,
        });
      } else if (type === 'featured_snippet' && !featuredSnippet) {
        const url = it?.url ?? '';
        featuredSnippet = {
          position: Number(it?.rank_group) || 0,
          title:    it?.title ?? '',
          url,
          domain:   it?.domain ? String(it.domain).replace(/^www\./, '') : extractDomain(url),
          snippet:  it?.description ?? undefined,
        };
      } else if (type === 'ai_overview') {
        hasAIO = true;
        aioSources = extractAioSources(it);
        aioText = extractAioText(it);
      } else if (type === 'people_also_ask') {
        for (const q of (Array.isArray(it?.items) ? it.items : [])) {
          const question = q?.title ?? '';
          if (question) paaQuestions.push(question);
          for (const e of (Array.isArray(q?.expanded_element) ? q.expanded_element : [])) {
            const url = e?.url ?? '';
            if (!url) continue;
            paaSources.push({
              question,
              title:  e?.title ?? '',
              url,
              domain: e?.domain ? String(e.domain).replace(/^www\./, '') : extractDomain(url),
            });
          }
        }
      } else if (type === 'video') {
        for (const v of (Array.isArray(it?.items) ? it.items : [])) {
          const url = v?.url ?? '';
          if (!url) continue;
          videoSources.push({
            title:   v?.title ?? '',
            url,
            domain:  extractDomain(url),
            channel: v?.source ?? undefined,
          });
        }
      }
    }

    const clientEntry = organicResults.find(r => isClient(r.domain, clientDomain));
    return {
      keyword,
      organicResults,
      hasAIO,
      aioSources,
      aioText,
      featuredSnippet,
      paaQuestions,
      paaClientCited:   paaSources.some(s => isClient(s.domain, clientDomain)),
      paaSources,
      serpFeatures:     itemTypes,
      videoClientCited: videoSources.some(s => isClient(s.domain, clientDomain)),
      videoSources,
      clientRank:       clientEntry ? clientEntry.position : null,
      scannedAt:        new Date().toISOString(),
      scannedBy:        'dataforseo' as const,   // v7.408: provenance travels WITH the row (Const I.1)
    };
  }

  for (let i = 0; i < batch.length; i += CONCURRENCY) {
    const slice = batch.slice(i, i + CONCURRENCY);
    const settled = await Promise.all(slice.map(k => scanOne(k).catch(() => null)));
    settled.forEach(r => { if (r) out.push(r); });
  }
  return out;
}

/** DataForSEO maps_search element → the MapsPlace shape serp.ts already returns. */
function parseDfsPlace(r: any, idx: number): MapsPlace {
  const reviewsRaw = r?.rating?.votes_count;
  return {
    title:    r?.title ?? '',
    placeId:  r?.place_id ?? r?.cid ?? '',
    address:  r?.address ?? '',
    rating:   typeof r?.rating?.value === 'number' ? r.rating.value : null,
    reviews:  typeof reviewsRaw === 'number' ? reviewsRaw : (parseInt(reviewsRaw, 10) || 0),
    type:     r?.category ?? '',
    website:  r?.url ?? r?.domain ?? '',
    phone:    r?.phone ?? '',
    lat:      typeof r?.latitude  === 'number' ? r.latitude  : null,
    lng:      typeof r?.longitude === 'number' ? r.longitude : null,
    position: Number(r?.rank_group) || idx + 1,
  };
}

/** Google Maps listings for a free-text query. Mirrors serp.ts getMapsListings. */
export async function dfsGetMapsListings(
  query: string,
  market?: Market,
  ll?: string,
  limit = 20,
): Promise<MapsPlace[]> {
  if (!dataForSeoEnabled()) return [];
  const m = market ?? getMarket('us');
  const coord = llToLocationCoordinate(ll);
  const task: Record<string, unknown> = {
    keyword: query,
    language_code: m.dfsLanguageCode,
    depth: Math.max(limit, 10),
  };
  if (coord) task.location_coordinate = coord;
  else task.location_name = m.dfsLocationName;

  const { result } = await dfsPost<any>(MAPS_ENDPOINT, task, 'google_maps');
  const items: any[] = Array.isArray(result?.items) ? result.items : [];
  return items
    .filter(i => i?.type === 'maps_search' || i?.title)
    .slice(0, limit)
    .map((r, i) => parseDfsPlace(r, i));
}

/**
 * The Google local 3-pack for a keyword as seen from a location. DataForSEO
 * returns it as a `local_pack` item inside the ORGANIC response (same place
 * SerpAPI puts `local_results`), so this reads the organic endpoint.
 */
export async function dfsGetLocalPack(
  keyword: string,
  market?: Market,
  ll?: string,
): Promise<LocalPackResult> {
  if (!dataForSeoEnabled()) return { packPresent: false, places: [] };
  const m = market ?? getMarket('us');
  const coord = llToLocationCoordinate(ll);
  const task: Record<string, unknown> = {
    keyword,
    language_code: m.dfsLanguageCode,
    device: 'desktop',
    depth: 10,
  };
  if (coord) task.location_coordinate = coord;
  else task.location_name = m.dfsLocationName;

  const { result } = await dfsPost<any>(ORGANIC_ENDPOINT, task, 'google_local_pack');
  const items: any[] = Array.isArray(result?.items) ? result.items : [];
  const packs = items.filter(i => i?.type === 'local_pack');
  // A local_pack item can be either one place per item, or a container with .items.
  const raw: any[] = [];
  packs.forEach(p => {
    if (Array.isArray(p?.items) && p.items.length) raw.push(...p.items);
    else raw.push(p);
  });
  const places = raw.slice(0, 3).map((r, i) => parseDfsPlace(r, i));
  return { packPresent: places.length > 0, places };
}

// ─── v7.426 · LLM Mentions (AI Optimization API) ─────────────────────────────
// Queries DataForSEO's index of RECORDED AI answers (ChatGPT + Google AI
// Overviews) for real questions containing a category's head keyword. Every
// field returned below is verbatim from the API payload (Const I.1) except
// `aiSearchVolume`, which DataForSEO documents as an ESTIMATED metric from its
// own algorithm — every consumer must label it as such (Const I.5a), never
// present it as measured demand. Cost is the measured per-task `cost` the API
// reports, recorded on the ledger under unit 'llm_mentions' (Const I.5b).
// Docs: https://docs.dataforseo.com/v3/ai_optimization/llm_mentions/search_mentions/live/

const LLM_MENTIONS_ENDPOINT = '/ai_optimization/llm_mentions/search_mentions/live';

export interface LlmMentionSource {
  domain: string;
  url:    string;
  title:  string;
}

export interface LlmMentionRow {
  platform:         string;              // 'chat_gpt' | 'google'
  modelName:        string;              // e.g. 'gpt-4o' / 'google_ai_overview'
  question:         string;              // the recorded prompt — verbatim
  answerExcerpt:    string;              // first 600 chars of the recorded answer (verbatim, truncated for storage)
  sources:          LlmMentionSource[];  // sources the model cited in its final answer
  searchResultDomains: string[];         // chat_gpt only: web-search result domains the model retrieved
  brandEntities:    string[];            // chat_gpt only: brands the answer named (API-extracted)
  aiSearchVolume:   number | null;       // DataForSEO ESTIMATED metric — label per I.5a, never measured demand
  webSearchBased:   boolean | null;      // whether the answer used live web search
  lastResponseAt:   string | null;       // when the recorded answer was last updated
}

export interface LlmMentionsResult {
  rows:       LlmMentionRow[];
  totalCount: number;                    // total matching rows in the index (we fetch up to `limit`)
  costUSD:    number;                    // measured task cost the API reported
}

/**
 * Fetch recorded AI answers whose QUESTION contains `keyword` (word-match).
 * Both platforms unless one is specified. `limit` defaults to 100 (the API's
 * own default page size); `totalCount` always reports the full match count so
 * the panel can disclose exactly how much of the index it is showing.
 */
export async function dfsSearchLlmMentions(
  keyword: string,
  opts: { limit?: number; platform?: 'chat_gpt' | 'google' } = {},
): Promise<LlmMentionsResult | null> {
  const kw = keyword.trim();
  if (!kw || !dataForSeoEnabled()) return null;
  const task: Record<string, unknown> = {
    target: [{ keyword: kw.slice(0, 250), search_filter: 'include', search_scope: ['question'], match_type: 'word_match' }],
    limit:  Math.min(Math.max(opts.limit ?? 100, 1), 1000),
  };
  if (opts.platform) task.platform = opts.platform;

  const { result, costUSD } = await dfsPost<any>(LLM_MENTIONS_ENDPOINT, task, 'llm_mentions_search', 'llm_mentions');
  if (!result) return null;

  const items: any[] = Array.isArray(result?.items) ? result.items : [];
  const rows: LlmMentionRow[] = items.map((it: any) => {
    const sources: LlmMentionSource[] = (Array.isArray(it?.sources) ? it.sources : [])
      .map((s: any) => ({
        domain: typeof s?.domain === 'string' ? s.domain.replace(/^www\./, '') : (typeof s?.url === 'string' ? extractDomain(s.url) : ''),
        url:    typeof s?.url === 'string' ? s.url : '',
        title:  typeof s?.title === 'string' ? s.title : (typeof s?.source_name === 'string' ? s.source_name : ''),
      }))
      .filter((s: LlmMentionSource) => !!s.domain);
    const srDomains = Array.from(new Set(
      (Array.isArray(it?.search_results) ? it.search_results : [])
        .map((r: any) => typeof r?.domain === 'string' ? r.domain.replace(/^www\./, '') : '')
        .filter(Boolean) as string[],
    ));
    const brands = (Array.isArray(it?.brand_entities) ? it.brand_entities : [])
      .map((b: any) => typeof b?.title === 'string' ? b.title : '')
      .filter(Boolean);
    const vol = Number(it?.ai_search_volume);
    return {
      platform:       String(it?.platform ?? ''),
      modelName:      String(it?.model_name ?? ''),
      question:       String(it?.question ?? '').slice(0, 500),
      answerExcerpt:  String(it?.answer ?? '').slice(0, 600),
      sources,
      searchResultDomains: srDomains,
      brandEntities:  brands,
      aiSearchVolume: Number.isFinite(vol) ? vol : null,
      webSearchBased: typeof it?.is_web_search_based === 'boolean' ? it.is_web_search_based : null,
      lastResponseAt: typeof it?.last_response_at === 'string' ? it.last_response_at : null,
    };
  }).filter((r: LlmMentionRow) => !!r.question);

  const totalCount = Number(result?.total_count);
  return { rows, totalCount: Number.isFinite(totalCount) ? totalCount : rows.length, costUSD };
}
